import Navbar from '@/components/Navbar'
import '../app/styles/globals.css'
import StateProviders from '@/context/StateProviders'

export const metadata = {
  title: 'Next.js MongoDB CRUD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='antialiased h-screen bg-gradient-to-br from-[#112D60] to-[#B6B0B5]'>
        <Navbar />
        <StateProviders>
          {children}
        </StateProviders>
      </body>
    </html>
  )
}
